---
title: "Untitled"
author: "wangzhuofan"
date: "2020/3/31"
output: html_document
---

--------step 1: generate GMM data--------

```{r}
library(mvtnorm)
library(rgl)
d <- 3
N <- 500
K <- 2
N1 <- 200
N2 <- 300
mu1 <- c(10,4,-10)
sigma1 <- diag(3)
mu2 <- c(5,-2,5)
sigma2 <- diag(3)
G1 <- rmvnorm(N1,mu1,sigma1)
G2 <- rmvnorm(N2,mu2,sigma2)
permutation <- sample(1:N,N)
x <- rbind(G1,G2)
plot3d(x)

```

--------step 2: EM algorithm--------

a,E-step

```{r}
Estep <- function(x,alpha,mu,sigma,K){
  p <- matrix(0,nrow = N,ncol = K)
  for (i in 1:N) {
    for (k in 1:K) {
      p[i,k] <- alpha[k]*dmvnorm(x[i,],mean = mu[k,],sigma = sigma[[k]])
    }
  }
  w <- p/rowSums(p)
  lpw <- list(p=p,w=w)
  return(lpw)
}

```

b,M-step

```{R}
Mstep <- function(x,w,mu,sigma,K){
  N_k <- colSums(w)
  alpha <- N_k/N
  for (k in 1:K) {
    musum <- 0
    sigsum <- matrix(0,nrow = d,ncol = d)
    for (i in 1:N) {
      temp1 <- w[i,k]*x[i,]
      musum <- musum + temp1
    }
    mu[k,] <- (1/N_k[k])*musum
    for (j in 1:N) {
      temp2 <- w[j,k]*(x[j,]-mu[k,])%*%t(x[j,]-mu[k,])
      sigsum <- sigsum + temp2
    }
    sigma[[k]] <- (1/N_k[k])*sigsum
  }
  lams <- list(alpha=alpha,mu=mu,sigma=sigma)
  return(lams)
}
```

c,EM-algorithm
```{r}
EM <- function(x,K,n,eps){
  K <- K
  count <- 0
  d <- ncol(x)
  N <- nrow(x)
  #initialize
  alpha <- rep(1/K,K)
  mu <- matrix(rnorm(K*d),nrow = K,ncol = d)
  sigma <- list(diag(d),diag(d))
  p <- matrix(0,nrow = N,ncol = K)
  for (i in 1:N) {
    for (k in 1:K) {
      p[i,k] <- alpha[k]*dmvnorm(x[i,],mean = mu[k,],sigma = sigma[[k]])
    }
  }
  log <- sum(log(apply(p, 1, sum)))
  repeat {
    #E-step
    w <- Estep(x,alpha,mu,sigma,K)$w
    #M-step
    alpha <- Mstep(x,w,mu,sigma,K)$alpha
    mu <- Mstep(x,w,mu,sigma,K)$mu
    sigma <- Mstep(x,w,mu,sigma,K)$sigma
    #derive the log-likelihood
    p <- Estep(x,alpha,mu,sigma,K)$p
    temp <- sum(log(apply(p, 1, sum)))
    count <- count+1
    if(abs(temp-log) < eps){
      print("converge to the solution!")
      break
    }
    else{
      log <- temp
    }
    if(count>n){
      print("run out of time!")
      break
    }
  }
  return(Mstep(x,w,mu,sigma,K))
}
```


--------step 3: tenser moments estimation--------

a,define a function to compute the m3
```{r}
m3_2_f <- function(x,s){
    m3_2 <-array(0,dim = c(d,d,d))
    for (i in 1:s) {
      temp <- x[i,]%o%x[i,]%o%x[i,]
      m3_2 <- m3_2+temp
  }
    m3_2 <- (1/s)*m3_2
    return(m3_2)
  }

```

b,define a function to compute weighted m3
```{r} 
m3_2_w_f <- function(Y,U,V,W){
  d1 <- ncol(U)
  d2 <- ncol(V)
  d3 <- ncol(W)
  result <- array(0,dim = c(d1,d2,d3))
  for (j1 in 1:d1) {
    for (j2 in 1:d2) {
      for (j3 in 1:d3) {
        sum <- 0
         
        for (i1 in 1:d) {
          for (i2 in 1:d) {
            for (i3 in 1:d) {
              t <- U[i1,j1]*V[i2,j2]*W[i3,j3]*Y[i1,i2,i3]
              sum <- sum+t
            }
          }
        }
        result[j1,j2,j3] <-sum
      }
    }
  }
  return(result)
}
```

c,define a function to compute weighted M3
```{r}
M3_2_w_f <- function(m3,U,V,W,sigma_1){
  d1 <- ncol(U)
  d2 <- ncol(V)
  d3 <- ncol(W)
  sum <- array(0,dim = c(d1,d2))
  e <- diag(d)
  for (i in 1:d) {
    t <- as.numeric(t(W)%*%e[i,])*(t(U)%*%mu_2)%*%t(t(V)%*%e[i,])+as.numeric(t(W)%*%e[i,])*(t(U)%*%e[i,])%*%t(t(V)%*%mu_2)+as.numeric(t(W)%*%mu_2)*(t(U)%*%e[i,])%*%t(t(V)%*%e[i,])
   
    sum <- sum+t
  }
  M3_2_w <- m3-sigma_1*sum
  return(M3_2_w)
}
```


```{R}
library(MASS)
library(expm)
Tensor_moment <- function(x,del){
  #derive the parameter
  N <- nrow(x)
  d <- ncol(x)
  s <- N/2
  s1 <- sample(1:N,s)
  x1 <- x[s1,]
  x2 <- x[-s1,]
  mu <- matrix(0,d,k)
  #starting computation using the first half
  mu_1 <- (1/s)*colSums(x1)#maen of the first half of sample
  m2_1 <- (1/s)*t(x1)%*%x1#second-order moment of the first half of sample
  sigma_1 <- eigen(m2_1-(mu_1)%*%t(mu_1))$values[k]#derive the \sigma^2
  svd <- svd(m2_1-sigma_1*diag(d),k,k)#get the svd
  m2_1 <- svd$u%*%diag(svd$d[1:k])%*%t(svd$v)#compite M_2
  u <- svd$u
  dp <- svd$d^(1/2)
  dm <- svd$d^(-1/2)
  w <- u%*%diag(dm[1:k])#w
  b <- u%*%diag(dp[1:k])#B
  #start computation using the second half
  mu_2 <- (1/s)*colSums(x2)
  ea <- t(w)%*%mu_2#weighted average
  

  #use the second half to compute m3
  m3_2 <- m3_2_f(x2,s)
  
  #use the second half to compute weighted m3
  m3_2_w <- m3_2_w_f(m3_2,w,w,w)
  
  #initiallize some parameter in the loop
  max_min <- 0
  times <- 0
  theta0 <- rep(0,k)
  eig0 <- rep(0,k)
  vec0 <- matrix(0,k,k)
  repeat{
    theta <- rmvnorm(1,rep(0,k),diag(k))
    theta <- theta/sqrt(sum(theta^2))
    eig <- eigen(M3_2_w_f(m3_2_w_f(m3_2,w,w,w%*%t(theta))[,,1],w,w,w%*%t(theta),sigma_1))$values
    vec <- eigen(M3_2_w_f(m3_2_w_f(m3_2,w,w,w%*%t(theta))[,,1],w,w,w%*%t(theta),sigma_1))$vectors
    dif <- min(abs(diff(eig)))
    ab <- min(abs(eig))
    temp <- min(dif,ab)
    if(temp > max_min){
      theta0 <- theta
      eig0 <- eig
      vec0 <- vec
    }
    
    times <- times+1
    if(times>-log2(del))
      break
  }
  for (i in 1:k) {
    mu[,i] <- as.numeric(eig0[i]/(theta0%*%(vec0[,i])))*b%*%vec0[,i]
  }
  weight <- ginv(mu)%*%mu_1
  return(list(mu=mu,weight=weight,sigma = sigma_1))
}
```


--------step 4: compare the accuracy and the speed--------
```{R}
system.time(EM(x,2,1000,1e-3))
system.time(Tensor_moment(x,0.95))
```